import type { Folder, VaultItem } from "@/types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000);

export const MOCK_FOLDERS: Folder[] = [
  {
    id: "root",
    userId: "demo-user",
    name: "Meu Vault",
    description: null,
    color: "violet",
    icon: "folder",
    parentId: null,
    order: 0,
    isRoot: true,
    itemCount: 4,
    folderCount: 3,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: "financas",
    userId: "demo-user",
    name: "Finanças",
    description: null,
    color: "emerald",
    icon: "folder",
    parentId: "root",
    order: 0,
    isRoot: false,
    itemCount: 2,
    folderCount: 1,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: "financas-2024",
    userId: "demo-user",
    name: "2024",
    description: null,
    color: "emerald",
    icon: "folder",
    parentId: "financas",
    order: 0,
    isRoot: false,
    itemCount: 3,
    folderCount: 1,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(3),
  },
  {
    id: "notas-fiscais",
    userId: "demo-user",
    name: "Notas Fiscais",
    description: null,
    color: "emerald",
    icon: "folder",
    parentId: "financas-2024",
    order: 0,
    isRoot: false,
    itemCount: 5,
    folderCount: 0,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
  },
  {
    id: "trabalho",
    userId: "demo-user",
    name: "Trabalho",
    description: null,
    color: "sky",
    icon: "folder",
    parentId: "root",
    order: 1,
    isRoot: false,
    itemCount: 8,
    folderCount: 2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: "pessoal",
    userId: "demo-user",
    name: "Pessoal",
    description: null,
    color: "rose",
    icon: "folder",
    parentId: "root",
    order: 2,
    isRoot: false,
    itemCount: 6,
    folderCount: 0,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },
];

export const MOCK_ITEMS: VaultItem[] = [
  {
    id: "item-1",
    userId: "demo-user",
    folderId: "root",
    type: "IMAGE",
    title: "Mesa nova do escritório",
    description: null,
    tags: ["casa", "referência"],
    color: "violet",
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600",
    fileKey: null,
    fileSize: 2_400_000,
    mimeType: "image/jpeg",
    codeLanguage: null,
    codeContent: null,
    noteContent: null,
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: "item-2",
    userId: "demo-user",
    folderId: "root",
    type: "NOTE",
    title: "Ideias para o aniversário",
    description: null,
    tags: ["planejamento"],
    color: "amber",
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: null,
    fileKey: null,
    fileSize: null,
    mimeType: null,
    codeLanguage: null,
    codeContent: null,
    noteContent: "# Aniversário\n\n- Reservar restaurante\n- Chamar os amigos\n- Bolo de chocolate",
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: "item-3",
    userId: "demo-user",
    folderId: "root",
    type: "SNIPPET",
    title: "debounce.ts",
    description: null,
    tags: ["utils", "typescript"],
    color: "sky",
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: null,
    fileKey: null,
    fileSize: null,
    mimeType: null,
    codeLanguage: "typescript",
    codeContent:
      "export function debounce<T extends (...args: unknown[]) => void>(fn: T, ms: number) {\n  let timer: ReturnType<typeof setTimeout>;\n  return (...args: Parameters<T>) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), ms);\n  };\n}",
    noteContent: null,
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    id: "item-4",
    userId: "demo-user",
    folderId: "root",
    type: "PASSWORD",
    title: "E-mail pessoal",
    description: null,
    tags: ["contas"],
    color: "rose",
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: null,
    fileKey: null,
    fileSize: null,
    mimeType: null,
    codeLanguage: null,
    codeContent: null,
    noteContent: null,
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: true,
    passwordStrength: "strong",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "item-5",
    userId: "demo-user",
    folderId: "notas-fiscais",
    type: "PDF",
    title: "NF-e 000234 — Fornecedor XPTO",
    description: null,
    tags: ["nf", "fornecedor"],
    color: "emerald",
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: "https://res.cloudinary.com/demo/image/upload/sample.pdf",
    fileKey: "sample.pdf",
    fileSize: 480_000,
    mimeType: "application/pdf",
    codeLanguage: null,
    codeContent: null,
    noteContent: null,
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "item-6",
    userId: "demo-user",
    folderId: "root",
    type: "LINK",
    title: "Designing Fluid Interfaces — WWDC18",
    description: null,
    tags: ["design", "referência"],
    color: "violet",
    isFavorite: true,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: "https://developer.apple.com/videos/play/wwdc2018/803/",
    fileKey: null,
    fileSize: null,
    mimeType: null,
    codeLanguage: null,
    codeContent: null,
    noteContent: null,
    linkOgTitle: "Designing Fluid Interfaces",
    linkOgDescription: "Apple Developer — WWDC 2018 session 803",
    linkOgImage: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600",
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: "item-7",
    userId: "demo-user",
    folderId: "root",
    type: "AUDIO",
    title: "Memo — ideia para o pitch",
    description: null,
    tags: ["voz"],
    color: "stone",
    isFavorite: false,
    isArchived: false,
    isDeleted: false,
    deletedAt: null,
    url: "https://res.cloudinary.com/demo/video/upload/sample.mp3",
    fileKey: "sample.mp3",
    fileSize: 1_200_000,
    mimeType: "audio/mpeg",
    codeLanguage: null,
    codeContent: null,
    noteContent: null,
    linkOgTitle: null,
    linkOgDescription: null,
    linkOgImage: null,
    linkFavicon: null,
    hasPassword: false,
    passwordStrength: null,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
];

export const MOCK_STORAGE = {
  used: 1_240_000_000,
  limit: 5 * 1024 * 1024 * 1024,
  plan: "pro" as const,
};

export const MOCK_USER = {
  id: "demo-user",
  name: "Ana Beatriz",
  email: "ana@exemplo.com",
  image: null as string | null,
};
